# One may have a look at http://docs.travis-ci.com/user/installing-dependencies/

language: c

notifications:
  - email: true

# Install the cross-compiler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version

# Several compilation options are checked
script:
  - make clean all
  - CFG_TEE_CLIENT_LOG_LEVEL=0 make clean all
  - CFG_TEE_CLIENT_LOG_LEVEL=5 make clean all
